# Dify 核心配置
model:
  provider: openai
  openai:
    api_key: "local"             # 本地模式固定值
    api_base: "http://model-api:8000"  # 模型服务地址
    model_name: "deepseek-1.3b-chat"   # 与模型文件名一致

knowledge:
  enabled: true                  # 启用知识库
  vector_store:
    type: faiss                  # 向量数据库类型
    path: "/data/vector_db"      # 容器内挂载路径
    embedding_model: "BAAI/bge-small-zh-v1.5"  # 嵌入模型

logging:
  level: INFO                    # 日志级别
  file: /var/log/dify.log        # 日志文件路径

# 高级参数（可选）
advanced:
  max_history: 5                 # 保留的历史对话轮次
  response_timeout: 30           # 响应超时时间（秒）